---
- name: create cloudwatch events
  cloudwatchevent_rule:
    name: "{{ item.0.rule_name }}"
    description: "{{ item.0.description }}"
    state: present
    event_pattern: "{{ lookup('file', './{{ item.0.event_pattern }}', convert_data=False) |string }}"
    targets:
      - id: "{{ item.1.name }}"
        arn: "{{ item.2.ansible_facts.function_arn }}"
  register: events
  with_together:
      - "{{ cloudwatch_events }}"
      - "{{ lambda_functions }}"
      - "{{ function_arns.results }}"
  tags: [create-cloudwatchevents]
